<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>LedCube</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.3.0" />
        <PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="8.3.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
        <PackageReference Include="Gamepad" Version="1.1.0" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\rpi-rgb-led-matrix\bindings\c#\RPiRgbLEDMatrix.csproj" />
      <ProjectReference Include="..\doom-sharp\src\DoomSharp.Core\DoomSharp.Core.csproj" />
    </ItemGroup>

</Project>
